### ISSUE TITLE
Typing "onna" results in "おんあ" instead of "おんな"

### ISSUE THREAD

**Issue by ianfhunter** [salemlf/hakubun#397] opened 2024-08-23 13:13 UTC
## Describe the Bug :bug:

On android, if you try typing "onna", it results in "おんあ" instead of "おんな".
To type "おんな", you must type "onnna".

I imagine this is due to the way the translation happens, that the n is not converted until it is definitely ん and not one of the n* hiragana (na,ni,no,nu,ne).

it's not a huge issue once you know about it, but it would be a nice QoL fix.

### Steps to Reproduce :paw_prints:

Type it into a review.

### Expected Behavior :relieved:

Explained above.

#### OS: (iOS, Android, etc.)
Android

#### App Version
v2.6.2-beta

**Comment by Shoghy** [comment] 2024-09-05 21:14
Writing `onna` with the Japanese keyboard on Windows and Android results in `おんあ` and I think that was the behavior on Linux with `fcitx5` I might be wrong with that last one, but I think that's the expected behavior.

**Comment by salemlf** [comment] 2024-10-26 20:13
@Shoghy is correct, this is expected behavior. This is how typing works through the Wanikani web app also, typing "n" twice to produce "ん" is necessary due to it possibly being standalone or the beginning or other sounds that begin with "n". [Here's an article](https://knowledge.wanikani.com/japanese/double-n/) from Wanikani explaining this. Closing this issue since it's working as expected!

**Closed by salemlf** 2024-10-26 20:13 UTC
Labels: bug
